version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/ssl/certs
    ports:
      - "443:443"
    depends_on:
      - jenkins
    restart: always

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    user: root
    volumes:
      - ./jenkins_data:/var/jenkins_home
    expose:
      - "8080"
    restart: always

volumes:
  jenkins_home: